resource_group_name    = "kv_terraform_rg"
location               = "West Europe"
keyvault_name          = "myvmvaultxyz"
secret_name            = "VMPassword"
secret_value           = "Microsoft@123"