resource_group_name     = "my_terraform_rg"
resource_group_location = "East US"
app_service_plan_name   = "my-appserviceplan"
app_service_name        = "terraform-appdb-0502"
sql_server_name         = "terraform-sqlserver-05029"
sql_database_name       = "ProductsDB"
sql_admin_login         = "testuser@97"
sql_admin_password      = "Microsoft@123"